artifact_location: /Users/adarshgyawali/Desktop/MLOps/MLOPS/MLOPS/MLFLOW_TRACKING_URI/0
creation_time: 1764114448004
experiment_id: '0'
last_update_time: 1764114448004
lifecycle_stage: active
name: Default
