artifact_location: /Users/adarshgyawali/Desktop/MLOps/MLOPS/MLOPS/MLFLOW_TRACKING_URI/912078790461424318
creation_time: 1764114448035
experiment_id: '912078790461424318'
last_update_time: 1764114448035
lifecycle_stage: active
name: VS_Code_credit_fraud_pipeline
